version: "3"

services:

  postgres-server:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres_password 
  redis-server:
    image: "redis:latest"

  nginx-server:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "80:80"
  
  main-server:
    build: 
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres-server
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432

  client-server:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app

  worker-server:
    build: 
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379

